#!/bin/sh

set -v

TAR_URL=https://hackage.haskell.org/package/unique-0/unique-0.tar.gz

pkgid=`basename $0`
tmpdir=`mktemp -d -t ${pkgid}` || exit 1
echo "Building in ${tmpdir}"    >&2

tar_fname=${tmpdir}/`basename ${TAR_URL}`

curl ${TAR_URL} -o ${tar_fname}
tar -C ${tmpdir} -xzf ${tar_fname}

(cd ${tmpdir}/${pkgid}; cabal install "${CABAL_INSTALL_OPTIONS}")
